object Versions {


    const val espressoCore = "3.5.1"
    const val extJunit = "1.1.5"
    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.7.20"
    const val appCompat = "1.3.0"
    const val material = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val hiltVersion = "2.44.2"
    const val multidexVersion = "2.0.1"
    const val lifecycleVersion = "2.5.1"
    const val fragmentKtx = "1.5.5"
    const val core = "1.9.0"
    const val navigationFragment = "2.5.3"
    const val navigationUi = "2.5.3"
    const val room = "2.5.0"
    const val retrofit = "2.9.0"
    const val saveArgs = "2.5.3"
    const val timber = "5.0.1"
    const val cameraView = "2.7.2"
    const val glide = "4.15.0"
    const val cropper = "0.3.2"
    const val okHttp = "4.9.3"
    const val okHttpInterceptor = "4.9.3"
    const val pagingVersion = "3.1.1"
}